name: Fork Repository
on:
  push:
    branches:
      - main
jobs:
  fork:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fork repository
        uses: actions/github-script@v4
        with:
          script: |
            const token = process.env.GITHUB_TOKEN;
            const octokit = github.getOctokit(token);
            const owner = 'freitas-labs';
            const repo = 'svelte-spa-sveltekit-ts-css-spike';
            const org = 'expensive-garbage'; // Replace with the target organization name

            async function forkRepo() {
              try {
                const response = await octokit.repos.createFork({
                  owner: owner,
                  repo: repo,
                  organization: 'expensive-garbage'
                });
                console.log(`Repository ${response.data.full_name} forked to organization ${org}`);
              } catch (error) {
                console.error('Failed to fork repository:', error);
              }
            }

            forkRepo();
