name: Fork Repository
on:
  push:
    branches:
      - main
jobs:
  fork:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Fork repository
      uses: actions/github-script@v4
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const result = await github.repos.createFork({
            owner: 'freitas-labs',
            repo: 'svelte-spa-sveltekit-ts-css-spike',
            organization: 'expensive-garbage'
          });
          console.log(result.data);